source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '10.24.0'
  pod 'Firebase/Core', '10.24.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
